# Application configuration for production environment
spring:
  welcome:
    message: "Hello from the Prod Profile!"
  data:
    mongodb:
      uri: mongodb://prod-db-server:27017/agrolink
  profiles:
    active: prod
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: localhost
        health-check-url-path: /actuator/health

