# Application configuration for production environment
welcome:
  message: "Hello from the Prod Profile!"
spring:
  data:
    mongodb:
      uri: mongodb+srv://souravkumarnayak612:iCmVMlIBTnW6OMQV@agrolink.bxuffhn.mongodb.net/agrolink?retryWrites=true&w=majority&appName=AgroLink
      

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      fallbackAddToCart: # Renamed to match the annotation
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5 # Changed to camelCase
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s # Changed to camelCase
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED