# Application configuration for production environment
welcome:
  message: "Hello from the Prod Profile!"
spring:
  data:
    mongodb:
      uri: mongodb+srv://souravkumarnayak612:iCmVMlIBTnW6OMQV@agrolink.bxuffhn.mongodb.net/agrolink?retryWrites=true&w=majority&appName=AgroLink
      

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always  


circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimum-number-of-calls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000