# Application configuration for production environment
welcome:
  message: "Hello from the Prod Profile!"
spring:
  data:
    mongodb:
      uri: mongodb+srv://souravkumarnayak612:iCmVMlIBTnW6OMQV@agrolink.bxuffhn.mongodb.net/agrolink?retryWrites=true&w=majority&appName=AgroLink
      

management:
  endpoints:
    web:
      exposure:
        include: health,info,ratelimiter

  endpoint:
    health:
      show-details: always