welcome:
    message: "Hello from the Default Profile!"
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: localhost
        health-check-url-path: /actuator/health
        
management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always